stages:
  - lint
  - test
  - build-app
  - docker-build-and-push
  - update-argo-image-staging
  - deploy-staging
  - post-deploy-staging
  - update-argo-image-production
  - deploy-production
  - post-deploy



#Pipeline import
include:
  - project: 'boldops/gitlab-ci-pipelines'
    ref: v1.1.0
    file:
      - 'jobs/js/jest.gitlab-ci.yaml'
      - 'jobs/js/lint.gitlab-ci.yaml'
      - 'jobs/js/yarn-build.gitlab-ci.yaml'
      - 'jobs/general/docker-build-and-push.gitlab-ci.yaml'
      - 'jobs/general/update-argo-image.gitlab-ci.yaml'
      - 'jobs/general/deploy.gitlab-ci.yaml'
      - 'jobs/general/cloudflare-cache-bust.gitlab-ci.yaml'

Lint:
  stage: lint
  interruptible: true
  only:
    refs:
      - main
      - merge_requests
  extends: .JSLint
  variables:
    WORKING_DIRECTORY: 'templates'

Test:
  stage: test
  interruptible: true
  only:
    refs:
      - main
      - merge_requests
  artifacts:
    reports:
      junit: ['templates/junit.xml']
  variables:
    WORKING_DIRECTORY: 'templates'
    KUBERNETES_CPU_REQUEST: 4000m
    KUBERNETES_CPU_LIMIT: 4000m
    KUBERNETES_MEMORY_REQUEST: 5000Mi
    KUBERNETES_MEMORY_LIMIT: 5000Mi
  extends: .JestTests

BuildApp:
  stage: build-app
  interruptible: true
  only:
    refs:
      - main
  artifacts:
    paths:
      - templates/build
  variables:
    WORKING_DIRECTORY: 'templates'
    KUBERNETES_CPU_REQUEST: 1000m
    KUBERNETES_CPU_LIMIT: 1000m
    KUBERNETES_MEMORY_REQUEST: 1024Mi
    KUBERNETES_MEMORY_LIMIT: 1024Mi
    RUNNER_IMAGE: node:12.14.1
  extends: .YarnBuild

DockerBuildAndPush:
  stage: docker-build-and-push
  only:
    - main
  variables:
    WORKING_DIRECTORY: 'templates'
    APP_NAME: checkout-experience-templates
    IMAGE_PROJECT: checkout-1236
  extends: .DockerBuildAndPush
  needs: [Lint, Test, BuildApp]

UpdateArgoImageStaging:
  stage: update-argo-image-staging
  only:
    - main
  variables:
    APP_NAME: checkout-experience-templates
    ENVIRONMENT: staging
    KUSTOMIZE_REPO: checkout-experience-templates
    IMAGE_VERSION_FILE: experience-templates-version
  extends: .UpdateArgoImage
  needs: [DockerBuildAndPush]

DeployStaging:
  stage: deploy-staging
  environment:
    name: staging
  only:
    - main
  variables:
    ENVIRONMENT: staging
    KUSTOMIZE_REPO: checkout-experience-templates
  extends: .Deploy
  needs: [UpdateArgoImageStaging]

CacheBustStaging:
  stage: post-deploy-staging
  only:
    - main
  variables:
    URL: 'checkout.staging.boldapps.net/assets/experience'
  extends: .CloudflareCacheBust
  needs: [DeployStaging]
  when: delayed
  start_in: 2 minutes

UpdateArgoImageProduction:
  stage: update-argo-image-production
  only:
    - main
  variables:
    APP_NAME: checkout-experience-templates
    ENVIRONMENT: production
    KUSTOMIZE_REPO: checkout-experience-templates
    IMAGE_VERSION_FILE: experience-templates-version
  extends: .UpdateArgoImage
  needs: [DeployStaging]

DeployProduction:
  stage: deploy-production
  environment:
    name: production
  when: manual
  only:
    - main
  variables:
    ENVIRONMENT: production
    KUSTOMIZE_REPO: checkout-experience-templates
  extends: .Deploy
  needs: [UpdateArgoImageProduction]

CacheBust:
  stage: post-deploy
  only:
    - main
  variables:
    URL: 'cashier.boldcommerce.com/assets/experience'
  extends: .CloudflareCacheBust
  needs: [DeployProduction]
  when: delayed
  start_in: 2 minutes
