stages:
  - lint
  - test
  - build

#Pipeline import
include:
  - project: 'boldops/gitlab-ci-pipelines'
    ref: master
    file:
      - 'jobs/js/jest.gitlab-ci.yaml'
      - 'jobs/js/lint.gitlab-ci.yaml'
      - 'jobs/js/node-build.gitlab-ci.yaml'

Lint:
  stage: lint
  interruptible: true
  only:
    refs:
      #- main
      - merge_requests
  extends: .JSLint

Tests:
  stage: test
  interruptible: true
  only:
    refs:
      #- main
      - merge_requests
  artifacts:
    reports:
      junit: ['junit.xml']
  variables:
    KUBERNETES_CPU_REQUEST: 4000m
    KUBERNETES_CPU_LIMIT: 4000m
    KUBERNETES_MEMORY_REQUEST: 5000Mi
    KUBERNETES_MEMORY_LIMIT: 5000Mi
  extends: .JestTests

Build:
  stage: build
  interruptible: true
  only:
    refs:
      - main
  artifacts:
    paths:
      - build
  variables:
    RUNNER_IMAGE: node:12.14.1
  extends: .NodeBuild
