stages:
  - lint
  - test
  - build-app
  - docker-build-and-push
  - update-argo-image-staging
  - deploy-staging
  - update-argo-image-production
  - deploy-production


#Pipeline import
include:
  - project: 'boldops/gitlab-ci-pipelines'
    ref: master
    file:
      - 'jobs/js/jest.gitlab-ci.yaml'
      - 'jobs/js/lint.gitlab-ci.yaml'
      - 'jobs/js/yarn-build.gitlab-ci.yaml'
      - 'jobs/general/docker-build-and-push.gitlab-ci.yaml'
      - 'jobs/general/update-argo-image.gitlab-ci.yaml'
      - 'jobs/general/deploy.gitlab-ci.yaml'

Lint:
  stage: lint
  interruptible: true
  only:
    refs:
      - main
      - merge_requests
  extends: .JSLint

Test:
  stage: test
  interruptible: true
  only:
    refs:
      - main
      - merge_requests
  artifacts:
    reports:
      junit: ['junit.xml']
  variables:
    KUBERNETES_CPU_REQUEST: 4000m
    KUBERNETES_CPU_LIMIT: 4000m
    KUBERNETES_MEMORY_REQUEST: 5000Mi
    KUBERNETES_MEMORY_LIMIT: 5000Mi
  extends: .JestTests

BuildApp:
  stage: build-app
  interruptible: true
  only:
    refs:
      - main
  artifacts:
    paths:
      - build
  variables:
    KUBERNETES_CPU_REQUEST: 1000m
    KUBERNETES_CPU_LIMIT: 1000m
    KUBERNETES_MEMORY_REQUEST: 1024Mi
    KUBERNETES_MEMORY_LIMIT: 1024Mi
    RUNNER_IMAGE: node:12.14.1
  extends: .YarnBuild

DockerBuildAndPush:
  stage: docker-build-and-push
  only:
    - main
  variables:
    APP_NAME: checkout-experience-templates
    IMAGE_PROJECT: checkout-1236
  extends: .DockerBuildAndPush
  needs: [Lint, Test, BuildApp]

UpdateArgoImageStaging:
  stage: update-argo-image-staging
  only:
    - main
  variables:
    APP_NAME: checkout-experience-templates
    ENVIRONMENT: staging
    KUSTOMIZE_REPO: checkout-experience-templates
    IMAGE_VERSION_FILE: experience-templates-version
  extends: .UpdateArgoImage
  needs: [DockerBuildAndPush]

DeployStaging:
  stage: deploy-staging
  environment:
    name: staging
  only:
    - main
  variables:
    ENVIRONMENT: staging
    KUSTOMIZE_REPO: checkout-experience-templates
  extends: .Deploy
  needs: [UpdateArgoImageStaging]

UpdateArgoImageProduction:
  stage: update-argo-image-production
  only:
    - main
  variables:
    APP_NAME: checkout-experience-templates
    ENVIRONMENT: prod
    KUSTOMIZE_REPO: checkout-experience-templates
    IMAGE_VERSION_FILE: checkout-experience-templates-version
  extends: .UpdateArgoImage
  needs: [DeployStaging]

DeployProduction:
  stage: deploy-production
  environment:
    name: production
  when: manual
  only:
    - main
  variables:
    ENVIRONMENT: prod
    KUSTOMIZE_REPO: checkout-experience-templates
  extends: .Deploy
  needs: [UpdateArgoImageProduction]
