stages:
  - lint
  - test

#Pipeline import
include:
  - project: 'boldops/gitlab-ci-pipelines'
    ref: master
    file:
      - 'jobs/js/jest.gitlab-ci.yaml'
      - 'jobs/js/lint.gitlab-ci.yaml'

Lint:
  stage: lint
  interruptible: true
  only:
    refs:
      - main
      - merge_requests
  variables: 
    RUNNER_IMAGE: node:12.14.1
  extends: .JSLint

Tests:
  stage: test
  interruptible: true
  only:
    refs:
      - main
      - merge_requests
  artifacts:
    reports:
      junit: ['bold-checkout-flows/junit.xml']
  extends: .JestTests