export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';
export const SET_LANGUAGE_ISO = 'SET_LANGUAGE_ISO';
export const SET_CALL_API_ON_EVENTS = 'SET_CALL_API_ON_EVENTS';
export const SET_PIGI_IFRAME_LOADER = 'SET_PIGI_IFRAME_LOADER';
export const SET_EXTERNAL_PAYMENT_GATEWAY_LOADING = 'SET_EXTERNAL_PAYMENT_GATEWAY_LOADING';
export const SET_LOADER = 'SET_LOADER';
export const SET_VALID = 'SET_VALID';
export const SET_EXTERNAL_PAYMENT_GATEWAY_VALID = 'SET_EXTERNAL_GATEWAY_VALID';
export const CLEAR_VALID_STATES = 'CLEAR_VALID_STATES';
export const SET_BUTTON_DISABLE = 'SET_BUTTON_DISABLE';
export const UPDATE_SCREEN_WIDTH = 'UPDATE_SCREEN_WIDTH';
export const UPDATE_BILLING_TYPE = 'UPDATE_BILLING_TYPE';
export const UPDATE_DISCOUNT_CODE_TEXT = 'UPDATE_DISCOUNT_CODE_TEXT';

export const SET_PIGI_DISPLAY_SCA = 'SET_PIGI_DISPLAY_SCA';
export const SET_EXPRESS_PAYMENT_SECTION_ENABLED = 'SET_EXPRESS_PAYMENT_SECTION_ENABLED';
export const ADD_PAYMENT = 'ADD_PAYMENT';
export const REMOVE_PAYMENT = 'REMOVE_PAYMENT';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const REMOVE_DISCOUNT = 'REMOVE_DISCOUNT';
export const UPDATE_DISCOUNTS = 'UPDATE_DISCOUNTS';
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const REMOVE_ERROR_BY_FIELD = 'REMOVE_ERROR_BY_FIELD';
export const REMOVE_ERROR_BY_TYPE = 'REMOVE_ERROR_BY_TYPE';
export const REMOVE_ERROR_BY_TYPE_AND_CODE = 'REMOVE_ERROR_BY_TYPE_AND_CODE';
export const REMOVE_FLASH_ERROR = 'REMOVE_FLASH_ERROR';
export const REMOVE_ERROR_BY_ADDRESS_TYPE = 'REMOVE_ERROR_BY_ADDRESS_TYPE';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_SELECTED_SHIPPING_LINE = 'SET_SELECTED_SHIPPING_LINE';
export const UPDATE_SELECTED_SHIPPING_LINE = 'UPDATE_SELECTED_SHIPPING_LINE';

export const UPDATE_AVAILABLE_SHIPPING_LINES = 'UPDATE_AVAILABLE_SHIPPING_LINES';
export const UPDATE_SHIPPING_LINES_TAXES = 'UPDATE_SHIPPING_LINES_TAXES';
export const UPDATE_SHIPPING_LINES_DISCOUNT = 'UPDATE_SHIPPING_LINES_DISCOUNT';

export const UPDATE_LINE_ITEMS = 'UPDATE_LINE_ITEMS';
export const UPDATE_TAXES = 'UPDATE_TAXES';
export const UPDATE_ORDER_TOTAL = 'UPDATE_ORDER_TOTAL';
export const UPDATE_ORDER_META_DATA = 'UPDATE_ORDER_META_DATA';
export const UPDATE_FEES = 'UPDATE_FEES';
export const UPDATE_PAYMENT_METHOD = 'UPDATE_PAYMENT_METHOD';

export const UPDATE_APP_DATA = 'UPDATE_APP_DATA';
export const UPDATE_ORDER_PROCESSED = 'UPDATE_ORDER_PROCESSED';

export const SET_SESSION_INITIALIZED = 'SET_SESSION_INITIALIZED';
